apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: centos8
  namespace: kubevirt-os-images
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/containerdisks/centos
    importPolicy:
      scheduled: true
    name: 8.4
